language: php
sudo: true

services:
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - git clone https://github.com/Alignak-monitoring-contrib/alignak-backend.git
  - cd alignak-backend
  - sudo pip install Flask==0.10.1
  - sudo pip install uwsgi
  - sudo python setup.py install
  - uwsgi -w alignakbackend:app --socket 0.0.0.0:5000 --protocol=http --enable-threads -p 4 &
  - cd ..

install:
  - composer install

before_script:
  - phpenv version-name | grep ^5.[34] && echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true
  - phpenv version-name | grep ^5.[34] && echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; true

script:
  - vendor/bin/phpunit tests/
  - if [[ "$TRAVIS_PHP_VERSION" == "5.4" ]]; then vendor/bin/phpcs src --standard=style/ruleset.xml -np; fi


